environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

image: Visual Studio 2017

cache:
  - packages -> **\packages.config

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: C:\ProgramData\chocolatey\bin\gfv.exe $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch

build_script:
  - ps: ./build.ps1

test: off

skip_tags: true

artifacts:
  - path: ./msbuild.log
  - path: ./artifacts/*.nupkg

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master

  - provider: Environment
    name: GitHub
    github_tag_name: v$(GitVersion_NuGetVersionV2)
    on:
      branch: master